[package]
name = "multihash"
version = "0.1.0"
authors = ["Eric Swanson <eswanson@alloscomp.com>"]
edition = "2018"

[dependencies]
rust-crypto = "^0.2"
crc = "^1.0.0"
integer-encoding = "^1.0.5"
byteorder = "1"
